name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        run: |
          yes | buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: growthjournal-apk
          path: bin/*.apk
